# https://github.com/alecthegeek/brewFile/blob/master/Brewfile

# Make sure we’re using the latest Homebrew.
brew update

# Upgrade any already-installed formulae.
brew upgrade

brew tap caskroom/cask
brew tap caskroom/versions

# brew tap dart-lang/dart
# brew install dart
brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew install ack
brew install bash
brew install bash-completion2
brew install cmake
brew install coreutils
# brew install elinks
# brew install fzf
# brew install ffmpeg
brew install git
brew install gnupg
brew install gnupg2
brew install go
# brew install highlight
brew install imagemagick
# brew install lastpass-cli --with-pinentry
brew install jq
brew install less
# brew install libgcrypt
# brew install lua
brew install neovim --HEAD
# brew install openssl
# brew install openssl@1.1
brew install postgres  # not postgresql
brew install python
brew install python@2
# brew install ranger
brew install readline
brew install reattach-to-user-namespace
# brew install shared-mime-info
brew install shellcheck
brew install sqlite
# brew install tag
# brew install tig
# brew install terminal-notifier
# brew install todo-txt
brew install tmux --HEAD
brew install tree
brew install unrar
brew install wget
brew install zsh

brew cask install atom
brew cask install alfred
brew cask install bartender
# brew cask install dropbox
brew cask install iina
brew cask install iterm2-nightly
brew cask install firefox
# brew cask install flux
brew cask install google-chrome
brew cask install google-chrome-canary
# brew cask install vienna
brew cask install visual-studio-code
# brew cask install vlc
brew cask install xquartz

brew cleanup

brew cask cleanup
