{
	"phony": {
		"prefix": "phony",
		"body": ".Phony: $0",
		"description": "A phony target is one that is not really the name of a file; rather it is just a name for a recipe to be executed when you make an explicit request.",
	}
}
