---
# Main Colors
unrecognized_file: orange
recognized_file:   coral
dir:               blue

# Link
dead_link: red
link:      cyan

# Access Modes
write:     darkkhaki
read:      limegreen
exec:      red
no_access: indianred

# Age
hour_old:    lime
day_old:     seagreen
no_modifier: green

# File Size
file_large:  orange
file_medium: gold
file_small:  dimgray

# Random
report: white
user:   cyan
tree:   cyan
empty:  darkgray
error:  red
normal: dimgray

# Git
addition:     chartreuse
modification: darkkhaki
deletion:     darkred
untracked:    darkorange
unchanged:    forestgreen
