ai:           "\ue7b4"
android:      "\ue70e"
# apple:        "\uf179"
apple:        "\ue711"
audio:        "\uf001"
avro:         "\ue60b"
bash:         "\ue14b" # 
zsh:          "\ue159" # 
c:            "\ue61e"
clj:          "\ue768"
coffee:       "\uf0f4"
conf:         "\ue615"
cpp:          "\ue61d"
css:          "\ue749"
d:            "\ue7af"
dart:         "\ue798"
db:           "\uf1c0"
diff:         "\uf440"
doc:          "\uf1c2"
ebook:        "\ue28b"
editorconfig: "\ue130" # 
env:          "\uf462"
epub:         "\ue28a"
erl:          "\ue7b1"
el:           "\ue14e" # 
lisp:         "\ue14d" # 
file:         "\uf15b"
font:         "\ue153" # 
gform:        "\uf298"
# git:          "\uf1d3"
git:          "\ue132" # 
go:           "\ue626"
gruntfile.js: "\ue74c"
graphql:      "\ue144" # 
hs:           "\ue777"
html:         "\uf13b"
image:        "\uf1c5"
iml:          "\ue7b5"
java:         "\ue204"
js:           "\ue74e" # 
json:         "\ue145" # 
data:         "\ue60b"
jsx:          "\ue7ba"
less:         "\ue758"
log:          "\uf18d"
lua:          "\ue620" # 
man:          "\ue151" # 
md:           "\uf48a"
mustache:     "\ue60f"
npmignore:    "\ue71e"
npmrc:        "\ue71e"
pdf:          "\uf1c1"
php:          "\ue73d"
pl:           "\ue769"
ppt:          "\uf1c4"
proselintrc:  "\ue156" # 
psd:          "\ue7b8"
py:           "\ue606" # 
r:            "\uf25d"
# rb:           "\ue21e"
rb:           "\uf219" #
rdb:          "\ue76d"
rss:          "\uf09e"
rubydoc:      "\ue73b"
sass:         "\ue603"
scala:        "\ue737"
shell:        "\uf489"
sqlite3:      "\ue7c4" # 
styl:         "\ue600"
tex:          "\ue600"
tex:          "\ue14f" # 
ts:           "\ue628"
twig:         "\ue61c"
txt:          "\uf15c"
video:        "\uf03d"
# vim:          "\ue62b"
vim:          "\ue7c5" # 
vue:          "\ue13d" # 
windows:      "\uf17a"
xls:          "\uf1c3"
xml:          "\ue619"
yarn.lock:    "\ue718"
yml:          "\ue706" # 
zip:          "\uf410"

Mercural:     "\ue11e" # 
Subversion:   "\ue11f" # 
X11:          "\ue120" # 
org:          "\ue15e" # 
fish:         "\ue14c" # 
ranger:       "\ue0f8" # 
# inputrc:      "\u" # 
