apk:              android
gradle:           android
ds_store:         apple
cfusertextencoding: apple
localized:        apple
mp3:              audio
ogg:              audio
scss:             sass
docx:             doc
gdoc:             doc
mobi:             ebook
eot:              font
otf:              font
ttf:              font
woff:             font
woff2:            font
gitconfig:        git
gitkeep:          git
gitignore:        git
gitignore_global: git
lhs:              hs
bmp:              image
gif:              image
ico:              image
jpeg:             image
jpg:              image
png:              image
svg:              image
jar:              java
properties:       json
tsx:              jsx
license:          md
markdown:         md
mkd:              md
rdoc:             md
readme:           md
gslides:          ppt
pptx:             ppt
pyc:              py
rdata:            r
rds:              r
gemfile:          rb
gemspec:          rb
guardfile:        rb
lock:             rb
procfile:         rb
rakefile:         rb
rspec:            rb
rspec_parallel:   rb
rspec_status:     rb
ru:               rb
erb:              rubydoc
slim:             rubydoc
sh:               shell
zsh-theme:        zsh
zshrc:            zsh
zsh_history:      zsh
zsh-update:       zsh
stylus:           styl
cls:              tex
avi:              video
mkv:              video
mp4:              video
ogv:              video
webm:             video
bat:              windows
exe:              windows
ini:              windows
csv:              xls
gsheet:           xls
xlsx:             xls
xul:              xml
yaml:             yml
gz:               zip
rar:              zip
tar:              zip

cson:         data
profile:      shell
aliases:      shell
functions:    shell
path:         shell
exports:      shell
xauthority:   X11
spacemacs:    el
bashrc:       bash
bash_profile: bash
bash_history: bash
inputrc:      bash
lesshst     : log

rc.conf:      ranger
rifle.conf:   ranger
scope.sh:     ranger
commands.py:  ranger
