.atom:        "\ue764"  # 
.cargo:       "\ue7a8"  # 
.git:         "\uf1d3"
.gem:         "\uf219"  # 
.github:      "\uf408"
.proselint:   "\ue156"  # 
.rvm:         "\ue21e"
.Trash:       "\uf1f8"  # 
.vscode:      "\ue70c"
config:       "\ue5fc"
# folder:      "\uf114"  # 
folder:       "\uf115"  # 
# folder:      "\uf07b"  # 
# folder:      "\uf07c"  # 
hidden:       "\uf023"
lib:          "\uf121"
node_modules: "\ue718"
bower_components: "\ue61a"  # 

# custom
gnu:          "\ue779"  # 
keys:         "\ue60a"  # 
.qutebrowser: "\uf26b"  # 
.dotfiles:    "\uf085"
.vim:         "\ue7c5"  # 
.npm:         "\ue71e"  # 
.tmux:        "\ue121"  # 
test:         "\uf0c3"  # 
Applications: "\ue713"  # 
Creative Cloud Files: "\ue137"  # 
Desktop:      "\uf108"  # 
Documents:    "\uf0c5"  # 
Downloads:    "\uf409"  # 
Docs:         "\ue171"  # 
docs:         "\ue171"  # 
Dropbox:      "\uf16b"
.dropbox:      "\uf16b"
Google Drive: "\ue731"  # 
Library:      "\ue119"  # 
Music:        "\uf025"  # 
Mail:         "\uf0e0"  # 
.Mail:        "\uf0e0"  # 
.mbox:        "\uf0e0"  # 
.mutt:        "\uf0e0"  # 
.task:        "\uf45e"  # 
.todo:        "\uf45e"  # 
Movies:       "\uf008"  # 
Pictures:     "\uf030"  # 
Projects:     "\uf414"  # 
aws:          "\ue7ad"  # 
Bash:         "\ue14b"  # 
Zsh:          "\ue159"  # 
Org:          "\ue15e"  # 
Fish:         "\ue14c"  # 
C:            "\ue61e"  # 
CPP:          "\ue61d"  # 
Docs:         "\uf48a"  # 
Electron:     "\ue140"  # 
Emacs:        "\ue13f"  # 
FontForge:    "\ue152"  # 
Go:           "\ue626"  #  
JS:           "\ue74e"  #
Lua:          "\ue620"  # 
Mercural:     "\ue11e"  # 
MySQL:        "\ue704"  # 
org:          "\ue15e" # 
PHP:          "\ue73d"  # 
php:          "\ue73d"
Python:       "\ue606"  # 
Ruby:         "\uf219"  #
shell:        "\ue159"  # 
Subversion:   "\ue11f"  # 
Vim:          "\ue7c5"  # 
vue:          "\ue13d"  # 
X11:          "\ue120"  # 
ranger:       "\ue0f8"  # 
