---
cmdargs:
  # Checking more strictly
  severity: style_problem

  # Enable coloring
  color: true

  # Enable Neovim syntax
  env:
    neovim: true

  # file_path
  # file_name
  # line_number
  # column_number
  # severity
  # description
  # policy_name
  # reference
  format: '{file_path}:{line_number}:{column_number}: {description}'

policies:
  # Style Problems
  ProhibitAbbreviationOption:
    enabled: true

  ProhibitImplicitScopeVariable:
    enabled: true

  # Warnings
  ProhibitAutocmdWithNoGroup:
    enabled: false

  ProhibitCommandRelyOnUser:
    enabled: true

  ProhibitCommandWithUnintendedSideEffect:
    enabled: true

  ProhibitEncodingOptionAfterScriptEncoding:
    enabled: true

  ProhibitEqualTildeOperator:
    enabled: true

  ProhibitImplicitScopeBuiltinVariable:
    enabled: true

  ProhibitMissingScriptEncoding:
    enabled: true

  ProhibitNoAbortFunction:
    enabled: true

  ProhibitSetNoCompatible:
    enabled: false

  ProhibitUnnecessaryDoubleQuote:
    enabled: true

  ProhibitUnusedVariable:
    enabled: true

  ProhibitUsingUndeclaredVariable:
    enabled: true
