# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

Metrics/LineLength:
  Enabled: true
  Max: 120

# Configuration parameters: EnforcedStyle.
# SupportedStyles: when_needed, always, never
Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false
