# https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/Next:
  Enabled: false

# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
